name: Self destruct

on:
  schedule:
    - cron: '0 0 20 2 *'
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository
        run: |
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.REPO_DELETE_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}
